### ISSUE TITLE
parameter refresh when storing a sysex patch

### ISSUE THREAD

**Issue by GuillaumeLeNost** [pingdynasty/OwlControl#1]
- load a sysex patch and store in slot 1 (lotka volterra)
- play a bit with this fun patch
- load a sysex patch and store in slot 2 (lorenz attractor)
  -> parameter B was not properly refreshed on UI.

**Comment by GuillaumeLeNost** [comment]
Same issue when load from file then run : parameters names aren't properly refreshed on UI.

**Comment by pingdynasty** [comment]
I can confirm that the same happens when loading a patch with OwlProgram `make run`.
I will try resetting when the app receives a PC message, which should happen right before the parameter names come in.
Otherwise I can reset when PARAMETER_A arrives, but if the patch doesn't use it then this won't work...

**Comment by pingdynasty** [comment]
fixed in v11
